services:
  db:
    container_name: peak_app_db
    build:
      context: ./apps/backend/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
